package io.ashu.protocol.command;

public interface PacketType {
  Byte LOING_REQUEST = 1;
  Byte LOING_RESPONSE = 2;
  Byte MESSAGE_REQUEST = 3;
  Byte MESSAGE_RESPONSE = 4;
  Byte CREATE_GROUP_REQUEST = 5;
  Byte CREATE_GROUP_RESPONSE = 6;
  Byte LIST_GROUP_MEMBERS_REQUEST = 7;
  Byte LIST_GROUP_MEMBERS_RESPONSE = 8;
  Byte GROUP_MESSAGE_REQUEST = 9;
  Byte GROUP_MESSAGE_RESPONSE = 10;
  Byte HEART_BEAT_REQUEST = 10;
  Byte HEART_BEAT_RESPONSE = 11;
}
